# Generated by Django 4.0.6 on 2022-07-12 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='run_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.run'),
            preserve_default=False,
        ),
    ]
