# Generated by Django 4.0.6 on 2022-07-14 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_attribute_class_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='run_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.run'),
            preserve_default=False,
        ),
    ]
