# Generated by Django 4.0.6 on 2022-07-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_relation_run_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='verb',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
