# Generated by Django 4.0.6 on 2022-07-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_relation_verb'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='multiplicity_1',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relation',
            name='multiplicity_2',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relation',
            name='phrase',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
