# Generated by Django 4.0.6 on 2022-07-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userextras_alter_run_user_fk_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='type',
            field=models.CharField(default='varchar(255)', max_length=50),
        ),
    ]
