# Generated by Django 4.0.6 on 2022-07-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_frequentattributes_technicality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prepositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
