# Generated by Django 4.0.6 on 2022-08-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_prepositions'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='run',
            name='type',
            field=models.CharField(default='nlp', max_length=5),
        ),
        migrations.AddField(
            model_name='userextras',
            name='money',
            field=models.FloatField(default=0.0),
        ),
    ]
