# Generated by Django 4.0.6 on 2022-08-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_run_correcion_manual_run_run_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='deleted',
        ),
        migrations.AddField(
            model_name='run',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
