# Generated by Django 4.0.6 on 2022-08-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_class_deleted_run_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextras',
            old_name='money',
            new_name='peticiones',
        ),
    ]
